BankTransactionSolution.Client/Controllers/BankAccountController.cs
using BankTransactionSolution.Domain.Entities;
using BankTransactionSolution.Domain.Model;
using BankTransactionSolution.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BankTransactionSolution.Client.Controllers
{
    public class BankAccountController : Controller
    {
        private readonly IBankAccountService _bankAccountService;

        public BankAccountController(IBankAccountService bankAccountService)
        {
            _bankAccountService = bankAccountService;
        }

        public async Task<IActionResult> GetBankAccount()
        {
            var userName = Request.Cookies["user_name"];

            if (string.IsNullOrEmpty(userName))
            {
                throw new Exception("user_name invalid");
            }
            var bankAccountList = await _bankAccountService.ListBankAccountAsync(userName);


            return Ok(bankAccountList);
        }

        public async Task<IActionResult> Index()
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return View("Index");
            }
            return View();
        }

        public async Task<BankAccountListModel> GetBankAccountDetail(int id)
        {
            var bankAccount = await _bankAccountService.GetSingleByCondition(t => t.id == id);
            return bankAccount;
        }

        public async Task<IEnumerable<BankAccountListModel>> GetListBankForUser()
        {
            var userName = Request.Cookies["user_name"];

            if (string.IsNullOrEmpty(userName))
            {
               throw new Exception("user_name invalid");
            }
            var bankAccount = await _bankAccountService.GetListBankForUser(userName);
            return bankAccount;
        }
    }
}

BankTransactionSolution.Client/Controllers/TransactionController.cs
using BankTransactionSolution.Domain.Model;
using BankTransactionSolution.Services.Imp;
using BankTransactionSolution.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace BankTransactionSolution.Client.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;

        public TransactionController(ITransactionService transactionService)
        {
            _transactionService = transactionService;
        }


        [HttpPost]
        public async Task<IActionResult> CreateTransaction([FromBody] UserTranferModel request)
        {
            try
            {
                if (request == null)
                {
                    return BadRequest("Dữ liệu không hợp lệ.");
                }

                var result = await _transactionService.UserTranfer(request);

                return Ok(new { success = result });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return StatusCode(500, "Lỗi hệ thống.");
            }
        }

        [HttpGet]
        public async Task<IEnumerable<TransactionHistoryModel>> GetTransactionHistories([FromQuery] int bank_account_id)
        {
            var result = await _transactionService.ListBankAccountHistoryAsync(bank_account_id);
            return result;
        }


        public IActionResult TransactionHistory()
        {
            return View();
        }
    }
}

BankTransactionSolution.Client/Controllers/UserController.cs
using BankTransactionSolution.Services.Imp;
using BankTransactionSolution.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace BankTransactionSolution.Client.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetUser()
        {
            try
            {
                var userName = Request.Cookies["user_name"];

                if (string.IsNullOrEmpty(userName))
                {
                    return BadRequest(new { message = "Không tìm thấy user_name trong cookies." });
                }

                var user = await _userService.GetUserWithConditionn(t => t.user_name == userName);

                if (user == null)
                {
                    return NotFound(new { message = "Không tìm thấy user." });
                }

                return Ok(user);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }

        }

        public async Task<IActionResult> UserDetail()
        {
            return View();
        }
    }
}

BankTransactionSolution.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankTransactionSolution.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/BankTransactionSolution.Client.styles.css" asp-append-version="true" /> *@

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <script src="@Url.Content("~/js/knockout-3.5.1.js")"></script>
    <script src="@Url.Content("~/vendor/bootstrap/js/bootstrap.bundle.min.js")"></script>
    <script src="@Url.Content("~/vendor/fontawesome-free/css/all.min.css")" rel="stylesheet" type="text/css"></script>
    <script src="@Url.Content("~/vendor/jquery/jquery.min.js")" rel="stylesheet" type="text/css"></script>
    <script src="@Url.Content("~/vendor/jquery-easing/jquery.easing.min.js")" rel="stylesheet" type="text/css"></script>
    <script src="@Url.Content("~/js/sb-admin-2.min.js")" rel="stylesheet" type="text/css"></script>
    <link rel="stylesheet" href="@Url.Content("~/css/sb-admin-2.min.css")">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <script src="~/Script/Common/Common.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" id="header">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" id="full_name"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BankAccount" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @* <img class="img-profile rounded-circle" id="userProfilePic" alt="User Image" style="width: 30px; height: 30px; margin-right: 10px;"> *@
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small" id="fullName"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="User" asp-action="UserDetail">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Hồ sơ
                                </a>
                                <a class="dropdown-item" asp-controller="Transaction" asp-action="TransactionHistory">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Lịch sử giao dịch
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng xuất
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Script/User/UserModel.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var viewModel = new UserModel();
            ko.applyBindings(viewModel, document.getElementById("header"));
        });

    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>